- src/sass/_modal.scss
потренировался в создании.
написал класс, который потом нужно дописывать
> создает паршал _modal.scss

- src/partials/modal.html
> Тестовый коммит

- src/partials/manufacture.html
- src/sass/_manufacture.scss
верстка и стили адаптированные под 3 точки перелома :)
> секция Manufacturing

- src/sass/_gallery.scss
Убрал верхний и нижний padding
> Removed the upper and lower padding

- src/partials/gallery.html
Исправил косяк с изображение в размере 320 X1
> fix-picture-source

- src/sass/_gallery.scss
- src/sass/config/_color-scheme.scss
> fix-gradient

- src/sass/_gallery.scss
- src/sass/config/_color-scheme.scss
Reverts Akunadjvili/command-project-markup#18
> Revert "fix-gradient"

- src/partials/gallery.html
- src/sass/_gallery.scss
> fix-width-section

- src/partials/gallery.html
- src/sass/_gallery.scss
Исправил ширину согласно принятого решения на встрече.
Новое значение 1280.
> fix-width-section-1280

- src/partials/manufacture.html
- src/sass/_manufacture.scss
- пофиксил несоответствия отступов после добаления галереи снизу
- отредактировал перенос строки в тексте
> 3 правки после проверки

- src/partials/hero.html
- src/sass/_hero.scss
Пофіксив плаваючі картинки та фон. 
Єдине що не зрозумів з приводу кнопок які зауваження ? 
На кнопки-посилання дав якорі, тільки на секціях їх не знайшов.
> Фікс позиціонування фонів та кнопок

- src/partials/page-footer.html
- src/sass/_page-footer.scss
В соответствиии с замечаниями на канале поменяла название ID и добавила префикс "f"ко всем стилям
> changing_ID_and_Namestyles

- src/partials/hero.html
- src/sass/_hero.scss
> Позиціонування картинок та тексту

- src/sass/_hero.scss
Вибачаюсь що відразу не закинув, такі дрібні відмінності, що не помітив відразу, але Вікторія зробила ревью та щойно ткнула носом у це)
> Позиціонування морозива та цифр на таблетці

- src/sass/_site-nav.scss
Исправил видимость мобильного меню на ширине 1200
> fix-nav-desktop menu on the visible

- src/partials/site-nav.html
> добавил aria-controls

- src/js/menu.js
- src/sass/_site-nav.scss
> анимация моб. меню + фокус

- src/index.html
- src/partials/site-nav.html
- src/sass/_site-nav.scss
Исправил z-index для навигации, фокус по кнопке buy now
> fix-z-index and btn buy now

- src/sass/_site-nav.scss
Исправил ховер по кнопке Buy now на всех разрешениях.
> fix-outline in the btn Buy now

- src/sass/_site-nav.scss
Reverts Akunadjvili/command-project-markup#75
> Revert "Update _site-nav.scss"

- src/index.html
- src/sass/_hero.scss
Исправил библиотеки js, ширину фона героя
> Исправил библиотеки js, ширину фона героя
